title:              HIGH HARMONICS
email:              HighHarmonics@protonmail.com
description:        Harmony Blockchain Validators | Running Nodes on stable cloud infrastructure with active monitoring
author:             High Harmonics Validators
baseurl:            ""
url:                "https://HighHarmonics.github.io"

# Social Profiles
twitter_username: HighHarmonics
github_username: HighHarmonics
facebook_username: HighHarmonics
instagram_username:  
linkedin_username:
staking_username: one1ramx2edudcn55ttt03derrm6kswe4t22eywar3
#[staking with us](https://staking.harmony.one/validators/mainnet/one1ramx2edudcn55ttt03derrm6kswe4t22eywar3)



# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
