title:              High Harmonics Validator
email:              HighHarmonics@protonmail.com
description:        Harmony Blockchain Validators | Running on stable cloud nfrastructure with active monitoring
                    
                    Come Stake with us https://google.com
author:             High Harmonics Validators
baseurl:            ""
url:                "https://HighHarmonics.github.io"

# Social Profiles
twitter_username: HighHarmonics
github_username: HighHarmonics
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
